# Generated by Django 5.0.4 on 2024-05-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applyingFor',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
